.\" Copyright (c) 2016, Tomohiro Kusumi
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice, this
.\"    list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
.\" ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.TH FILEOBJ 1 "May 6, 2018" "FILEOBJ 0.7.67"
.nh
.ad l
.SH NAME
fileobj \- ncurses based hex editor with vi interface
.SH SYNOPSIS
.PD 0
\fBfileobj\fP [\fIoptions\fP]... [\fIpaths\fP]...
.PP
\fBfileobj\fP [\fIoptions\fP]... [\fIpaths\fP[\fI@offset:length\fP]]...
.PP
\fBfileobj\fP [\fIoptions\fP]... [\fIpaths\fP[\fI@offset\-(offset+length)\fP]]...
.PD
.SH DESCRIPTION
\fBfileobj\fP provides basic vi commands for binary editing.
Features include inserting and replacing data in hexadecimal or ascii, deleting data, cut and paste, undo and redo, visual select, multiple buffers and windows, partial file loading, raw disk/partition support, \fBptrace\fP\|(2) based userspace editing, data in C struct view, etc.
.SH OPTIONS
.PP
\fB\-\-version\fP
.RS 4
Print version and exit.
.RE
.PP
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Print help message and exit.
.RE
.PP
\fB\-R\fP
.RS 4
Use read\-only mode.
.RE
.PP
\fB\-B\fP
.RS 4
Use \fBmalloc\fP\|(3) based buffer for regular files instead of the default \fBmmap\fP\|(2) based buffer.
This option is required to resize (i.e. insert or delete) regular files on platforms without \fBmremap\fP\|(2).
.RE
.PP
\fB\-d\fP
.RS 4
Show the buffer offset from \fIoffset\fP to \fIoffset+length\fP rather than from \fI0\fP to \fIlength\fP, when the buffer is partially loaded.
.RE
.PP
\fB\-x\fP
.RS 4
Show the buffer size and current position in hexadecimal.
.RE
.PP
\fB\-o\fP
.RS 4
Initially assign buffers given by \fIpaths\fP to horizontally splitted windows, if the terminal has enough size to accommodate.
.RE
.PP
\fB\-O\fP
.RS 4
Initially assign buffers given by \fIpaths\fP to vertically splitted windows, if the terminal has enough size to accommodate.
.RE
.PP
\fB\-\-bytes_per_line\fP=\fI<bytes_per_line>\fP, \fB\-\-bpl\fP=\fI<bytes_per_line>\fP
.RS 4
Set fixed number of bytes printed per line.
Each line prints \fI<bytes_per_line>\fP bytes, if the terminal has enough width to accommodate.
Available formats for \fI<bytes_per_line>\fP are digit, "max", "min" and "auto".
"auto" sets the value to the maximum 2^N that fits in the terminal width.
"auto" is used by default.
.RE
.PP
\fB\-\-bytes_per_window\fP=\fI<bytes_per_window>\fP, \fB\-\-bpw\fP=\fI<bytes_per_window>\fP
.RS 4
Set fixed number of bytes printed per window.
Each window prints \fI<bytes_per_window>\fP bytes, if the terminal has enough size to accommodate.
This option sets number of lines printed per window, based on the number of bytes printed per line.
Available formats for \fI<bytes_per_window>\fP are digit, "even" and "auto".
"even" does not set a fixed number of bytes printed per window, but makes all windows have the same size when a new window is vertically added.
"auto" is used by default.
.RE
.PP
\fB\-\-fg\fP=\fI<color>\fP
.RS 4
Set foreground color of the terminal.
Available colors for \fI<color>\fP are "black", "blue", "cyan", "green", "magenta", "red", "white" and "yellow".
"black" is used by default.
This option is not supported on VTxxx terminal emulators.
.RE
.PP
\fB\-\-bg\fP=\fI<color>\fP
.RS 4
Set background color of the terminal.
Available colors for \fI<color>\fP are "black", "blue", "cyan", "green", "magenta", "red", "white" and "yellow".
"white" is used by default.
This option is not supported on VTxxx terminal emulators.
.RE
.PP
\fB\-\-verbose_window\fP
.RS 4
Use verbose status window instead of the default format.
.RE
.PP
\fB\-\-backup\fP
.RS 4
Explicitly create backup files for regular files.
Backup files are created under \fI~/.fileobj\fP when \fBfileobj\fP starts, and removed when \fBfileobj\fP terminates.
Backup files start with '.'.
This option only applies to regular files.
.RE
.PP
\fB\-\-force\fP
.RS 4
Ignore warnings which can be ignored by specifying this option.
.RE
.PP
\fB\-\-test_screen\fP
.RS 4
Enter \fBncurses\fP\|(3) screen test mode.
.RE
.PP
\fB\-\-command\fP
.RS 4
Print list of editor commands and exit.
.RE
.PP
\fB\-\-sitepkg\fP
.RS 4
Print \fBpython\fP\|(1) site\-package directory and exit.
.RE
.SH COMMANDS
See \fB\-\-command\fP option in \fBOPTIONS\fP.
.SH FILES
.PP
\fI~/.fileobj\fP
.RS 4
A directory automatically created by \fBfileobj\fP.
.RE
.PP
\fI~/.fileobj/cstruct\fP
.RS 4
A default file path for \fB:cstruct\fP command.
.RE
.PP
\fI~/.fileobj/history\fP
.RS 4
A JSON file contains history of executed editor commands.
.RE
.PP
\fI~/.fileobj/log\fP
.RS 4
A file contains logged messages.
.RE
.PP
\fI~/.fileobj/marks\fP
.RS 4
A JSON file contains per\-file marks marked by an editor command.
.RE
.PP
\fI~/.fileobj/session\fP
.RS 4
A JSON file contains session information.
.RE
.PP
\fI~/.fileobj/.YYYY\-MM\-DD\-HH:MM:SS.path\-to\-file.bak\fP
.RS 4
Temporary backup file format for \fB\-\-backup\fP option.
.RE
.SH RESOURCE
.PD 0
\fIhttps://sourceforge.net/projects/fileobj/\fP
.PP
\fIhttps://github.com/kusumi/fileobj/\fP
.PD
.SH DOCUMENTATION
\fIhttps://github.com/kusumi/fileobj/blob/master/README.md\fP
.SH COPYING
Copyright (c) 2010\-2018, Tomohiro Kusumi.
Free use of this software is granted under the terms of the BSD License (2\-clause).
.SH AUTHORS
Tomohiro Kusumi <\fIkusumi.tomohiro@gmail.com\fP>
